insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
insert into student (no,name,roma,sex,phone,email,postno,address1,address2,address3,address4,birthday,graduation) values (
